# Generated by Django 3.2.16 on 2023-01-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultNamingWord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Default Naming Word Id')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Default Naming Word Title')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Register Date')),
                ('mod_date', models.DateTimeField(auto_now_add=True, verbose_name='Modify Date')),
            ],
            options={
                'db_table': 'default_naming_word',
            },
        ),
    ]
