# Generated by Django 3.2.16 on 2023-01-09 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_defaultnamingword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naming',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Naming Id')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Naming Title')),
                ('like', models.IntegerField(default=0, verbose_name='Like')),
                ('visit', models.IntegerField(default=0, verbose_name='Visit')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Register Date')),
                ('mod_date', models.DateTimeField(auto_now_add=True, verbose_name='Modify Date')),
            ],
            options={
                'db_table': 'naming',
            },
        ),
        migrations.RenameField(
            model_name='defaultnamingword',
            old_name='title',
            new_name='word',
        ),
        migrations.CreateModel(
            name='NamingWord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Naming Word Id')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='Naming Word Title')),
                ('sort', models.IntegerField(default=0, verbose_name='Sort')),
                ('depth', models.IntegerField(default=0, verbose_name='Depth')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Register Date')),
                ('mod_date', models.DateTimeField(auto_now_add=True, verbose_name='Modify Date')),
                ('naming_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.naming', verbose_name='Naming Id')),
            ],
            options={
                'db_table': 'naming_word',
            },
        ),
    ]
